var ModelList = {
// Lenny cost
	data: [
		new Model('Lady Justice', 'Guild', ['Master', 'Living', 'Guild Marshal'], undefined, 4),
		new Model('Sonnia Criid', 'Guild', ['Master', 'Living', 'Witch Hunter'], undefined, 3),
		new Model('Perdita Ortega', 'Guild', ['Master', 'Living', 'Family'], undefined, 2),
		new Model('Franscisco Ortega', 'Guild', ['Henchman', 'Living', 'Family'], 8, 5),
		new Model('Samael Hopkins', 'Guild', ['Henchman', 'Living', 'Witch Hunter'], 9, 4),
		new Model('The Judge', 'Guild', ['Henchman', 'Living', 'Rare 1', 'Guild Marshal'], 9, 4),
		new Model('Scales of Justice', 'Guild', ['Peon', 'Living', 'Totem (Lady Justice)'], 3),
		new Model('Purifying Flame', 'Guild', ['Peon', 'Totem (Sonnia Criid)', 'Spirit'], 3),
		new Model('Enslaved Nephilim', 'Guild', ['Peon', 'Totem (Perdita Ortega)', 'Nephilim'], 3),
		new Model('Governor\'s Proxy', 'Guild', ['Peon', 'Totem', 'Living'], 3),
		new Model('Death Marshal', 'Guild', ['Minion', 'Living', 'Guild Marshal'], 6),
		new Model('Executioner', 'Guild', ['Enforcer', 'Living', 'Rare 2'], 9),
		new Model('Guild Austringer', 'Guild', ['Minion', 'Living', 'Rare 2', 'Guardsman'], 6),
		new Model('Guild Guard', 'Guild', ['Minion', 'Living', 'Guardsman'], 4),
		new Model('Peacekeeper', 'Guild', ['Enforcer', 'Construct', 'Rare 1'], 11),
		new Model('The Lone Marshal', 'Guild', ['Enforcer', 'Living', 'Rare 1', 'Guild Marshal'], 8),
		new Model('Witchling Stalker', 'Guild', ['Minion', 'Living', 'Witch Hunter'], 5),
		new Model('Nino Ortega', 'Guild', ['Enforcer', 'Living', 'Rare 1', 'Family'], 7),
		new Model('Papa Loco', 'Guild', ['Enforcer', 'Living', 'Rare 1', 'Family', 'Tormented'], 7),
		new Model('Santiago Ortega', 'Guild', ['Enforcer', 'Living', 'Rare 1', 'Family'], 7),
		
		new Model('Seamus', 'Resurrectionist', ['Master', 'Living'], undefined, 3),
		new Model('McMorning', 'Resurrectionist', ['Master', 'Living'], undefined, 4),
		new Model('Nicodem', 'Resurrectionist', ['Master', 'Living'], undefined, 3),
		new Model('Madam Sybelle', 'Resurrectionist', ['Henchman', 'Undead', 'Rare 1'], 8, 5),
		new Model('Sebastian', 'Resurrectionist', ['Henchman', 'Living', 'Rare 1'], 7, 6),
		new Model('Mortimer', 'Resurrectionist', ['Henchman', 'Living', 'Rare 1'], 9, 4),
		new Model('Copycat Killer', 'Resurrectionist', ['Peon', 'Living', 'Totem (Seamus)'], 3),
		new Model('Zombie Chihuahua', 'Resurrectionist', ['Peon', 'Undead', 'Totem (McMorning)', 'Beast'], 2),
		new Model('Vulture', 'Resurrectionist', ['Peon', 'Living', 'Totem (Nicodem)', 'Beast'], 3),
		new Model('Graveyard Spirit', 'Resurrectionist', ['Peon', 'Totem', 'Spirit'], 3),
		new Model('Bete Noire', 'Resurrectionist', ['Enforcer', 'Undead', 'Rare 1'], 8),
		new Model('Canine Remains', 'Resurrectionist', ['Minion', 'Undead'], 4),
		new Model('Crooked Man', 'Resurrectionist', ['Minion', 'Undead'], 5),
		new Model('Flesh Construct', 'Resurrectionist', ['Minion', 'Undead', 'Construct'], 6),
		new Model('Mindless Zombie', 'Resurrectionist', ['Peon', 'Undead'], 2),
		new Model('Necropunk', 'Resurrectionist', ['Minion', 'Undead', 'Construct'], 5),
		new Model('Nurse', 'Resurrectionist', ['Minion', 'Living', 'Tormented'], 5),
		new Model('Punk Zombie', 'Resurrectionist', ['Minion', 'Undead', 'Horror'], 7),
		new Model('Rotten Belle', 'Resurrectionist', ['Minion', 'Undead', 'Belle'], 5),
		new Model('The Hanged', 'Resurrectionist', ['Minion', 'Undead', 'Rare 2', 'Spirit', 'Tormented'], 9),
		
		new Model('Rasputina', 'Arcanist', ['Master', 'Living'], undefined, 3),
		new Model('Marcus', 'Arcanist', ['Master', 'Living'], undefined, 4),
		new Model('Ramos', 'Arcanist', ['Master', 'Living'], undefined, 3),
		new Model('Myranda', 'Arcanist', ['Henchman', 'Living', 'Rare 1', 'Beast'], 8, 5),
		new Model('Joss', 'Arcanist', ['Henchman', 'Living', 'Construct', 'Rare 1', 'M&SU'], 10, 3),
		new Model('Cojo', 'Arcanist', ['Enforcer', 'Living', 'Rare 1', 'Beast'], 8),
		new Model('Ice Golem', 'Arcanist', ['Enforcer', 'Construct'], 10),
		new Model('Wendigo', 'Arcanist', ['Minion', 'Living', 'Totem (Rasputina)'], 3),
		new Model('Jackalope', 'Arcanist', ['Peon', 'Living', 'Totem (Marcus)', 'Beast'], 2),
		new Model('Brass Arachnid', 'Arcanist', ['Peon', 'Construct', 'Totem (Ramos)', 'M&SU'], 4),
		new Model('Essence of Power', 'Arcanist', ['Peon', 'Totem', 'Spirit'], 3),
		new Model('December Acolyte', 'Arcanist', ['Minion', 'Living'], 7),
		new Model('Electric Creation', 'Arcanist', ['Peon', 'Construct'], 4),
		new Model('Hoarcat Pride', 'Arcanist', ['Minion', 'Living', 'Beast', 'Swarm'], 5),
		new Model('Howard Langston', 'Arcanist', ['Enforcer', 'Construct', 'Living', 'Rare 1', 'M&SU'], 12),
		new Model('Ice Gamin', 'Arcanist', ['Minion', 'Construct', 'Gamin'], 4),
		new Model('Metal Gamin', 'Arcanist', ['Minion', 'Construct', 'Gamin', 'M&SU', 'Foundry'], 4),
		new Model('Moleman', 'Arcanist', ['Minion', 'Living', 'Beast'], 4),
		new Model('Rail Golem', 'Arcanist', ['Enforcer', 'Construct', 'Rare 1'], 11),
		new Model('Razorspine Rattler', 'Arcanist', ['Minion', 'Living', 'Beast'], 7),
		new Model('Sabertooth Cerberus', 'Arcanist', ['Enforcer', 'Living', 'Beast'], 9),
		new Model('Steam Arachnid', 'Arcanist', ['Minion', 'Construct', 'M&SU'], 4),
		new Model('Steam Arachnid Swarm', 'Arcanist', ['Minion', 'Construct', 'Swarm', 'M&SU'], 8),
		
		new Model('Lilith', 'Neverborn', ['Master', 'Living', 'Nephilim'], undefined, 4),
		new Model('Pandora', 'Neverborn', ['Master', 'Living', 'Woe'], undefined, 3),
		new Model('Zoraida', 'Neverborn', ['Master', 'Living', 'Swampfiend'], undefined, 4),
		new Model('Barbaros', 'Neverborn', ['Henchman', 'Living', 'Rare 1', 'Nephilim'], 10, 3),
		new Model('Candy', 'Neverborn', ['Henchman', 'Living', 'Rare 1', 'Woe', 'Mimic', 'Lost'], 9, 4),
		new Model('Bad Juju', 'Neverborn', ['Henchman', 'Rare 1', 'Swampfiend'], 8, 5),
		new Model('Cherub', 'Neverborn', ['Peon', 'Living', 'Totem (Lilith)', 'Nephilim'], 3),
		new Model('Poltergeist', 'Neverborn', ['Minion', 'Totem (Pandora)', 'Woe', 'Spirit'], 5),
		new Model('Voodoo Doll', 'Neverborn', ['Peon', 'Construct', 'Totem (Zoraida)', 'Puppet'], 3),
		new Model('Primordial Magic', 'Neverborn', ['Peon', 'Totem', 'Spirit'], 2),
		new Model('Baby Kade', 'Neverborn', ['Enforcer', 'Living', 'Rare 1', 'Woe', 'Lost'], 7),
		new Model('Teddy', 'Neverborn', ['Enforcer', 'Construct', 'Nightmare'], 11),
		new Model('Beckoner', 'Neverborn', ['Minion', 'Living', 'Rare 2', 'Brilliance', 'Darkened', 'Mimic'], 7),
		new Model('Doppleganger', 'Neverborn', ['Enforcer', 'Living', 'Rare 1', 'Woe', 'Mimic'], 7),
		new Model('Mature Nephilim', 'Neverborn', ['Enforcer', 'Living', 'Nephilim'], 11),
		new Model('Silurid', 'Neverborn', ['Minion', 'Living', 'Beast', 'Swampfiend'], 7),
		new Model('Sorrow', 'Neverborn', ['Minion', 'Woe', 'Spirit'], 5),
		new Model('Terror Tot', 'Neverborn', ['Minion', 'Living', 'Nephilim'], 4),
		new Model('Waldgeist', 'Neverborn', ['Minion', 'Living', 'Beast', 'Swampfiend'], 6),
		new Model('Young Nephilim', 'Neverborn', ['Minion', 'Living', 'Nephilim'], 6),
		
		new Model('Von Schill', 'Outcast', ['Master', 'Living', 'Freikorps'], undefined, 1),
		new Model('Tara', 'Outcast', ['Master', 'Undead'], undefined, 4),
		new Model('Viktoria of Ashes', 'Outcast', ['Master', 'Living'], undefined, 1),
		new Model('Hannah', 'Outcast', ['Henchman', 'Living', 'Rare 1', 'Mercenary'], 10, 3),
		new Model('The Nothing Beast', 'Outcast', ['Enforcer', 'Rare 1'], 10),
		new Model('Viktoria of Blood', 'Outcast', ['Henchman', 'Living', 'Rare 1', 'Sister'], 0, 3),
		new Model('Taelor', 'Outcast', ['Henchman', 'Living', 'Mercenary', 'Rare 1'], 10, 3),
		new Model('Steam Trunk', 'Outcast', ['Peon', 'Construct', 'Totem (Von Schill)'], 3),
		new Model('Karina', 'Outcast', ['Enforcer', 'Living', 'Totem (Tara)'], 5),
		new Model('Student of Conflict', 'Outcast', ['Peon', 'Living', 'Totem', 'Mercenary', 'Sister'], 4),
		new Model('Malifaux Child', 'Outcast', ['Peon', 'Living', 'Totem', 'Mercenary', 'Lost'], 2),
		new Model('Bishop', 'Outcast', ['Enforcer', 'Living', 'Mercenary', 'Rare 1'], 10),
		new Model('Convict Gunslinger', 'Outcast', ['Enforcer', 'Living', 'Mercenary', 'Rare 2'], 7),
		new Model('Desperate Gunslinger', 'Outcast', ['Minion', 'Living', 'Mercenary'], 4),
		new Model('Freikorps Specialist', 'Outcast', ['Living', 'Enforcer', 'Mercenary', 'Freikorps'], 8),
		new Model('Freikorpsman', 'Outcast', ['Living', 'Minion', 'Mercenary', 'Freikorps'], 5),
		new Model('Hans', 'Outcast', ['Enforcer', 'Living', 'Mercenary', 'Rare 1'], 8),
		new Model('Johan', 'Outcast', ['Enforcer', 'Living', 'Mercenary', 'Rare 1', 'M&SU'], 6),
		new Model('Killjoy', 'Outcast', ['Enforcer', 'Undead', 'Mercenary', 'Rare 1', 'Horror'], 12),
		new Model('Ronin', 'Outcast', ['Minion', 'Living', 'Mercenary'], 6),
		new Model('Void Wretch', 'Outcast', ['Minion'], 4),
		
		new Model('Som\'er Teeth Jones', 'Gremlin', ['Master', 'Living', 'Gremlin'], undefined, 4),
		new Model('Ophelia LaCroix', 'Gremlin', ['Master', 'Living', 'Gremlin', 'Kin'], undefined, 3),
		new Model('The Brewmaster', 'Gremlin', ['Master', 'Living', 'Gremlin', 'Tri-chi'], undefined, 3),
		new Model('Francois LaCroix', 'Gremlin', ['Henchman', 'Living', 'Rare 1', 'Gremlin', 'Kin'], 7, 6),
		new Model('Fingers', 'Gremlin', ['Henchman', 'Living', 'Rare 1', 'Gremlin', 'Tri-chi'], 10, 3),
		new Model('Lenny', 'Gremlin', ['Enforcer', 'Living', 'Rare 1', 'Gremlin'], 10),
		new Model('Whisky Golem', 'Gremlin', ['Enforcer', 'Construct', 'Rare 1', 'Tri-chi'], 10),
		new Model('Skeeter', 'Gremlin', ['Peon', 'Living', 'Totem (Som\er Teeth Jones)'], 2),
		new Model('Young LaCroix', 'Gremlin', ['Peon', 'Living', 'Totem (Ophelia LaCroix)', 'Gremlin', 'Kin'], 2),
		new Model('Apprentice Wesley', 'Gremlin', ['Minion', 'Living', 'Totem (The Brewmaster)', 'Gremlin', 'Tri-chi'], 3),
		new Model('Bayou Gremlin', 'Gremlin', ['Minion', 'Living', 'Gremlin'], 3),
		new Model('Hog Whisperer', 'Gremlin', ['Minion', 'Living', 'Mercenary', 'Gremlin'], 5),
		new Model('Moon Shinobi', 'Gremlin', ['Minion', 'Living', 'Gremlin', 'Tri-chi'], 6),
		new Model('Pigapult', 'Gremlin', ['Peon', 'Construct', 'Rare 1', 'Gremlin'], 8),
		new Model('Piglet', 'Gremlin', ['Minion', 'Living', 'Beast', 'Pig'], 4),
		new Model('Slop Hauler', 'Gremlin', ['Minion', 'Living', 'Gremlin'], 5),
		new Model('War Pig', 'Gremlin', ['Minion', 'Living', 'Beast', 'Pig'], 9),
		new Model('Pere Ravage', 'Gremlin', ['Enforcer', 'Living', 'Rare 1', 'Gremlin', 'Kin'], 6),
		new Model('Rami LaCroix', 'Gremlin', ['Enforcer', 'Living', 'Rare 1', 'Gremlin', 'Kin'], 7),
		new Model('Raphael LaCroix', 'Gremlin', ['Enforcer', 'Living', 'Rare 1', 'Gremlin', 'Kin'], 7),
		
		new Model('Misaki', 'Ten Thunders', ['Master', 'Living', 'Last Blossom'], undefined, 2),
		new Model('Mei Feng', 'Ten Thunders', ['Master', 'Living', 'Foundry'], undefined, 3),
		new Model('Jakob Lynch', 'Ten Thunders', ['Master', 'Living', 'Darkened'], undefined, 1),
		new Model('Ototo', 'Ten Thunders', ['Henchman', 'Living', 'Rare 1', 'Last Blossom'], 10, 3),
		new Model('Kang', 'Ten Thunders', ['Henchman', 'Living', 'Rare 1', 'Foundry'], 9, 4),
		new Model('Yamaziko', 'Ten Thunders', ['Henchman', 'Living', 'Rare 1', 'Last Blossom'], 7, 6),
		new Model('Shang', 'Ten Thunders', ['Peon', 'Living', 'Totem (Misaki)'], 3),
		new Model('Emberling', 'Ten Thunders', ['Minion', 'Totem (Mei Feng)', 'Spirit'], 3),
		new Model('Hungering Darkness', 'Ten Thunders', ['Henchman', 'Totem (Jakob Lynch)', 'Rare 1', 'Spirit', 'Darkened'], 0, 5),
		new Model('Dawn Serpent', 'Ten Thunders', ['Minion', 'Living', 'Rare 1', 'Beast'], 10),
		new Model('Fuhatsu', 'Ten Thunders', ['Henchman', 'Living', 'Rare 1'], 10, 3),
		new Model('Monk of Low River', 'Ten Thunders', ['Minion', 'Living', 'Rare 3'], 4),
		new Model('Oiran', 'Ten Thunders', ['Minion', 'Living', 'Mercenary', 'Last Blossom', 'Showgirl'], 5),
		new Model('Rail Worker', 'Ten Thunders', ['Minion', 'Living', 'Construct', 'Foundry'], 5),
		new Model('The Illuminated', 'Ten Thunders', ['Minion', 'Living', 'Brilliance'], 7),
		new Model('Thunder Archer', 'Ten Thunders', ['Minion', 'Living'], 7),
		new Model('Torakage', 'Ten Thunders', ['Minion', 'Living', 'Mercenary', 'Last Blossom'], 6),
		new Model('Samurai', 'Ten Thunders', ['Enforcer', 'Living'], 8)		
	]
};