var UpgradeList = {
	data: [
		new Upgrade('Plant Evidence', ['Guild'], ['Upgrade', 'Rare 3'], 1),
		new Upgrade('Vengeance Bullet', ['Guild'], ['Upgrade', 'Master', 'Henchman', 'Rare 1'], 1),
		new Upgrade('Lead Lined Coat', ['Guild'], ['Upgrade', 'Henchman', 'Enforcer', 'Living', 'Rare 3'], 2),
		new Upgrade('The Thalarian Stone', ['Guild'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Badge of Office', ['Guild'], ['Upgrade', 'Leader', 'Limited'], 2),
		new Upgrade('Implacable', ['Guild'], ['Upgrade', 'Lady Justice'], 1),
		new Upgrade('Justice Unleashed', ['Guild'], ['Upgrade', 'Lady Justice'], 1),
		new Upgrade('Last Stand', ['Guild'], ['Upgrade', 'Lady Justice'], 1),
		new Upgrade('Vendetta', ['Guild'], ['Upgrade', 'Lady Justice', 'Limited'], 2),
		new Upgrade('Unrelenting Leader', ['Guild'], ['Upgrade', 'The Judge'], 2),
		new Upgrade('Flames of the Pit', ['Guild'], ['Upgrade', 'Guild Marshal', 'Rare 1'], 2),
		new Upgrade('Cherufe\'s Imprint', ['Guild'], ['Upgrade', 'Sonnia'], 1),
		new Upgrade('Reincarnation', ['Guild'], ['Upgrade', 'Sonnia', 'Limited'], 1),
		new Upgrade('The Mask', ['Guild'], ['Upgrade', 'Sonnia'], 1),
		new Upgrade('Counterspell Aura', ['Guild'], ['Upgrade', 'Sonnia'], 1),
		new Upgrade('Witch Hunt', ['Guild'], ['Upgrade', 'Samael Hopkins'], 2),
		new Upgrade('Disrupt Magic', ['Guild'], ['Upgrade', 'Witch Hunter', 'Rare 1'], 2),
		new Upgrade('Os Veo', ['Guild'], ['Upgrade', 'Perdita'], 2),
		new Upgrade('Trick Shooting', ['Guild'], ['Upgrade', 'Perdita'], 2),
		new Upgrade('Aura Ancestral', ['Guild'], ['Upgrade', 'Perdita'], 1),
		new Upgrade('Tormenta de Plomo', ['Guild'], ['Upgrade', 'Family', 'Rare 1'], 1),
		new Upgrade('Diestro', ['Guild'], ['Upgrade', 'Family', 'Rare 1'], 3),
		new Upgrade('Hermanos De Armas', ['Guild'], ['Upgrade', 'Family', 'Rare 1'], 1),
		new Upgrade('Wade In', ['Guild'], ['Upgrade', 'Franscisco Ortega'], 1),
		
		new Upgrade('Unnerving Aura', ['Resurrectionist'], ['Upgrade', 'Rare 3'], 1),
		new Upgrade('Decaying Aura', ['Resurrectionist'], ['Upgrade', 'Rare 1'], 2),
		new Upgrade('Transfusion', ['Resurrectionist'], ['Upgrade', 'Rare 2'], 1),
		new Upgrade('Maniacal Laugh', ['Resurrectionist'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Corpse Bloat', ['Resurrectionist'], ['Upgrade', 'Master', 'Henchman', 'Rare 1'], 2),
		new Upgrade('Asylum Stone', ['Resurrectionist'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Sinister Reputation', ['Resurrectionist'], ['Upgrade', 'Seamus', 'Limited'], 1),
		new Upgrade('Red Chapel Killer', ['Resurrectionist'], ['Upgrade', 'Seamus'], 1),
		new Upgrade('Not Too Banged Up', ['Resurrectionist'], ['Upgrade', 'Seamus', 'Madam Sybelle', 'Rare 1'], 1),
		new Upgrade('Bag O\' Tools', ['Resurrectionist'], ['Upgrade', 'Seamus', 'Limited'], 1),
		new Upgrade('Mad Haberdasher', ['Resurrectionist'], ['Upgrade', 'Seamus'], 2),
		new Upgrade('Bleeding Tongue', ['Resurrectionist'], ['Upgrade', 'Madame Sybelle'], 1),
		new Upgrade('Plastic Surgery', ['Resurrectionist', 'Guild'], ['Upgrade', 'McMourning'], 1),
		new Upgrade('Evidence Tampering', ['Resurrectionist', 'Guild'], ['Upgrade', 'McMourning'], 2),
		new Upgrade('Moonlighting', ['Resurrectionist'], ['Upgrade', 'McMourning'], 1),
		new Upgrade('On the Clock', ['Guild'], ['Upgrade', 'McMourning'], 1),
		new Upgrade('Unknowable Pain', ['Resurrectionist', 'Guild'], ['Upgrade', 'McMourning', 'Sebastian', 'Rare 1'], 1),
		new Upgrade('Those Are Not Ours!', ['Resurrectionist'], ['Upgrade', 'Sebastian'], 1),
		new Upgrade('Undertaker', ['Resurrectionist'], ['Upgrade', 'Nicodem'], 1),
		new Upgrade('Reaper Grin', ['Resurrectionist'], ['Upgrade', 'Nicodem'], 1),
		new Upgrade('Shadow Embrace', ['Resurrectionist'], ['Upgrade', 'Nicodem'], 1),
		new Upgrade('Necrotic King', ['Resurrectionist'], ['Upgrade', 'Nicodem'], 2),
		new Upgrade('My Favorite Shovel', ['Resurrectionist'], ['Upgrade', 'Mortimer'], 2),
		new Upgrade('Love Thy Master', ['Resurrectionist'], ['Upgrade', 'Nicodem', 'Mortimer', 'Rare 1'], 1),
		
		new Upgrade('Imbued Protection', ['Arcanist'], ['Upgrade', 'Rare 2'], 2),
		new Upgrade('Imbued Energies', ['Arcanist'], ['Upgrade', 'Rare 3'], 1),
		new Upgrade('The Philosopher\'s Stone', ['Arcanist'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Arcane Reservoir', ['Arcanist'], ['Upgrade', 'Leader'], 2),
		new Upgrade('Recharge Soulstone', ['Arcanist'], ['Upgrade', 'Master', 'Henchman', 'Rare 2'], 1),
		new Upgrade('December\'s Pawn', ['Arcanist'], ['Upgrade', 'Rasputina'], 2),
		new Upgrade('Cold Nights', ['Arcanist'], ['Upgrade', 'Rasputina'], 1),
		new Upgrade('Child of December', ['Arcanist'], ['Upgrade', 'Rasputina'], 1),
		new Upgrade('Shattered Heart', ['Arcanist'], ['Upgrade', 'Rasputina', 'Limited'], 3),
		new Upgrade('Armor of December', ['Arcanist'], ['Upgrade', 'Frozen Heart', 'Limited', 'Rare 2'], 1),
		new Upgrade('Sub Zero', ['Arcanist'], ['Upgrade', 'Frozen Heart', 'Rare 1'], 1),
		new Upgrade('Feral Instinct', ['Arcanist'], ['Upgrade', 'Marcus'], 1),
		new Upgrade('The Hunger Cry', ['Arcanist'], ['Upgrade', 'Marcus'], 1),
		new Upgrade('The Trail of the Gods', ['Arcanist'], ['Upgrade', 'Marcus', 'Limited'], 1),
		new Upgrade('The God\'s Domain', ['Arcanist'], ['Upgrade', 'Marcus', 'Limited'], 1),
		new Upgrade('Skinwalker', ['Arcanist'], ['Upgrade', 'Myranda'], 1),
		new Upgrade('Pack Leader', ['Arcanist'], ['Upgrade', 'Beast', 'Rare 1'], 1),
		new Upgrade('Field Generator', ['Arcanist'], ['Upgrade', 'Ramos'], 2),
		new Upgrade('Combat Mechanic', ['Arcanist'], ['Upgrade', 'Ramos'], 2),
		new Upgrade('Electric Summoning', ['Arcanist'], ['Upgrade', 'Ramos'], 1),
		new Upgrade('Under Pressure', ['Arcanist'], ['Upgrade', 'Ramos'], 2),
		new Upgrade('Open Current', ['Arcanist'], ['Upgrade', 'Joss'], 1),
		new Upgrade('Bleeding Edge Tech', ['Arcanist'], ['Upgrade', 'M&SU', 'Rare 1'], 1),
		
		new Upgrade('Pact', ['Neverborn'], ['Upgrade', 'Rare 3'], 1),
		new Upgrade('Fears Given Form', ['Neverborn'], ['Upgrade', 'Master', 'Henchman', 'Rare 2'], 1),
		new Upgrade('Nexus of Power', ['Neverborn'], ['Upgrade', 'Henchman', 'Enforcer', 'Rare 1'], 1),
		new Upgrade('Stone of Tyrant Echoes', ['Neverborn'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Aether Conections', ['Neverborn'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Beckon Malifaux', ['Neverborn'], ['Upgrade', 'Lilith'], 1),
		new Upgrade('Living Blade', ['Neverborn'], ['Upgrade', 'Lilith'], 2),
		new Upgrade('Wicked Mistress', ['Neverborn'], ['Upgrade', 'Lilith'], 1),
		new Upgrade('Summon the Blood', ['Neverborn'], ['Upgrade', 'Lilith'], 1),
		new Upgrade('Nephilim Gladiatus', ['Neverborn'], ['Upgrade', 'Barbaros'], 1),
		new Upgrade('Obsidian Talons', ['Neverborn'], ['Upgrade', 'Nephilim', 'Rare 1'], 1),
		new Upgrade('Rapid Growth', ['Neverborn'], ['Upgrade', 'Nephilim', 'Rare 1'], 1),
		new Upgrade('Fugue State', ['Neverborn'], ['Upgrade', 'Pandora'], 2),
		new Upgrade('Cry for Me', ['Neverborn'], ['Upgrade', 'Pandora'], 2),
		new Upgrade('The Box Opens', ['Neverborn'], ['Upgrade', 'Pandora', 'Limited'], 2),
		new Upgrade('Voices', ['Neverborn'], ['Upgrade', 'Pandora', 'Limited'], 1),
		new Upgrade('Depression', ['Neverborn'], ['Upgrade', 'Woe', 'Rare 1'], 1),
		new Upgrade('Best Behavior', ['Neverborn'], ['Upgrade', 'Candy'], 1),
		new Upgrade('Animal Shape', ['Neverborn', 'Gremlin'], ['Upgrade', 'Zoraida', 'Limited'], 2),
		new Upgrade('Crystal Ball', ['Neverborn', 'Gremlin'], ['Upgrade', 'Zoraida', 'Limited'], 2),
		new Upgrade('Tarot Reading', ['Neverborn', 'Gremlin'], ['Upgrade', 'Zoraida'], 2),
		new Upgrade('Hex Bag', ['Neverborn', 'Gremlin'], ['Upgrade', 'Zoraida'], 1),
		new Upgrade('Eternal Fiend', ['Neverborn'], ['Upgrade', 'Bad Juju'], 2),
		new Upgrade('Hexed Among You', ['Neverborn', 'Gremlin'], ['Upgrade', 'Swampfiend', 'Rare 1'], 1),
		
		new Upgrade('Scramble', ['Outcast'], ['Upgrade', 'Limited', 'Rare 3'], 2),
		new Upgrade('Tally Sheet', ['Outcast'], ['Upgrade', 'Master', 'Henchman', 'Rare 2'], 1),
		new Upgrade('The Traveler\'s Stone', ['Outcast'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Survivivalist', ['Outcast'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Oath Keeper', ['Outcast'], ['Upgrade', 'Rare 3'], 1),
		new Upgrade('Paid in Blood', ['Outcast'], ['Upgrade', 'Von Schill'], 2),
		new Upgrade('Paid in Blood', ['Outcast'], ['Upgrade', 'Von Schill'], 2),
		new Upgrade('Engage at Will', ['Outcast'], ['Upgrade', 'Von Schill'], 1),
		new Upgrade('The Shirt Comes Off', ['Outcast'], ['Upgrade', 'Von Schill'], 1),
		new Upgrade('Ancient Tomes', ['Outcast'], ['Upgrade', 'Hannah'], 2),
		new Upgrade('Spoils of War', ['Outcast'], ['Upgrade', 'Freikrops', 'Master', 'Henchman', 'Rare 1'], 1),
		new Upgrade('Eternal Journey', ['Outcast', 'Resurrectionist'], ['Upgrade', 'Tara'], 1),
		new Upgrade('Knowledge of Eternity', ['Outcast', 'Resurrectionist'], ['Upgrade', 'Tara'], 2),
		new Upgrade('Obliteration Symbiote', ['Outcast', 'Resurrectionist'], ['Upgrade', 'Tara'], 2),
		new Upgrade('Dead of Winters', ['Outcast', 'Resurrectionist'], ['Upgrade', 'Tara'], 1),
		new Upgrade('Voiceless Words', ['Outcast', 'Resurrectionist'], ['Upgrade', 'Nothing Beast', 'Tara', 'Rare 1'], 1),
		new Upgrade('Long Forgotten Magics', ['Outcast', 'Resurrectionist'], ['Upgrade', 'Karina'], 1),
		new Upgrade('Sisters in Spirit', ['Outcast'], ['Upgrade', 'Sister', 'Rare 1'], 1),
		new Upgrade('Sisters in Fury', ['Outcast'], ['Upgrade', 'Viktoria of Blood', 'Viktoria of Ash', 'Rare 1'], 2),
		new Upgrade('Howling Wolf Tattoo', ['Outcast'], ['Upgrade', 'Sister', 'Rare 1'], 1),
		new Upgrade('Mark of Shez\'uul', ['Outcast'], ['Upgrade', 'Sister', 'Rare 1'], 2),
		new Upgrade('Synchronized Slaying', ['Outcast'], ['Upgrade', 'Sister', 'Rare 1'], 2),
		
		new Upgrade('Liquid Bravery', ['Gremlin'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Quality Mash Liquor', ['Gremlin'], ['Upgrade', 'Master', 'Henchman', 'Rare 1'], 2),
		new Upgrade('Dirty Cheater', ['Gremlin'], ['Upgrade', 'Rare 2'], 1),
		new Upgrade('The Guardian Stone', ['Gremlin'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Show Off', ['Gremlin'], ['Upgrade', 'Gremlin', 'Rare 1'], 1),
		new Upgrade('Stilts', ['Gremlin'], ['Upgrade', 'Gremlin', 'Rare 1'], 1),
		new Upgrade('Pig Feed', ['Gremlin'], ['Upgrade', 'Somer'], 1),
		new Upgrade('Family Tree', ['Gremlin'], ['Upgrade', 'Somer'], 2),
		new Upgrade('Can \'o Beans', ['Gremlin'], ['Upgrade', 'Somer'], 1),
		new Upgrade('Encouragement', ['Gremlin'], ['Upgrade', 'Somer'], 2),
		new Upgrade('I\'ll Love It and Pet it...', ['Gremlin'], ['Upgrade', 'Lenny'], 1),
		new Upgrade('Binge', ['Gremlin', 'Ten Thunders'], ['Upgrade', 'The Brewmaster'], 1),
		new Upgrade('Hold Their Hari Back', ['Gremlin', 'Ten Thunders'], ['Upgrade', 'The Brewmaster'], 1),
		new Upgrade('Running Tab', ['Gremlin', 'Ten Thunders'], ['Upgrade', 'The Brewmaster'], 2),
		new Upgrade('The Good Stuff', ['Gremlin', 'Ten Thunders'], ['Upgrade', 'The Brewmaster'], 1),
		new Upgrade('Drinking "Problem"', ['Gremlin', 'Ten Thunders'], ['Upgrade', 'Tri\'chi', 'Rare 1'], 1),
		new Upgrade('Angry Drunk', ['Gremlin', 'Ten Thunders'], ['Upgrade', 'Whiskey Golem'], 2),
		new Upgrade('Hooch Igniter', ['Gremlin'], ['Upgrade', 'Ophelia'], 1),
		new Upgrade('Jug Rocket', ['Gremlin'], ['Upgrade', 'Ophelia'], 1),
		new Upgrade('My Threatenin\' Gun', ['Gremlin'], ['Upgrade', 'Ophelia'], 1),
		new Upgrade('Gremlin-See', ['Gremlin'], ['Upgrade', 'Kin', 'Rare 2'], 1),
		new Upgrade('Team Work', ['Gremlin'], ['Upgrade', 'Kin', 'Rare 3'], 1),
		
		new Upgrade('Servent of 5 Dragons', ['Ten Thunders'], ['Upgrade', 'Rare 3'], 1),
		new Upgrade('Broken Promises', ['Ten Thunders'], ['Upgrade', 'Master', 'Henchman', 'Rare 2'], 2),
		new Upgrade('Recalled Training', ['Ten Thunders'], ['Upgrade', 'Master', 'Henchman', 'Rare 3'], 1),
		new Upgrade('Dragon Stone', ['Ten Thunders'], ['Upgrade', 'Leader'], 1),
		new Upgrade('Misdirection', ['Ten Thunders'], ['Upgrade', 'Leader'], 2),
		new Upgrade('Disguise', ['Ten Thunders', 'Outcast'], ['Upgrade', 'Misaki', 'Limited'], 2),
		new Upgrade('Cutpurse', ['Ten Thunders', 'Outcast'], ['Upgrade', 'Misaki'], 1),
		new Upgrade('Untouchable', ['Ten Thunders', 'Outcast'], ['Upgrade', 'Misaki'], 1),
		new Upgrade('Stalking Bisento', ['Ten Thunders', 'Outcast'], ['Upgrade', 'Misaki', 'Limited'], 2),
		new Upgrade('Smoke & Shadows', ['Ten Thunders', 'Outcast'], ['Upgrade', 'Last Blossom', 'Rare 1'], 1),
		new Upgrade('Call the Thunder', ['Ten Thunders'], ['Upgrade', 'Ototo'], 1),
		new Upgrade('Thunderous Smash', ['Ten Thunders', 'Arcanist'], ['Upgrade', 'Mei Feng'], 1),
		new Upgrade('Seismic Claws', ['Ten Thunders', 'Arcanist'], ['Upgrade', 'Mei Feng'], 1),
		new Upgrade('Price of Progress', ['Ten Thunders', 'Arcanist'], ['Upgrade', 'Mei Feng'], 1),
		new Upgrade('Vapormancy', ['Ten Thunders', 'Arcanist'], ['Upgrade', 'Mei Feng'], 1),
		new Upgrade('People\'s Challenge', ['Ten Thunders', 'Arcanist'], ['Upgrade', 'Kang'], 2),
		new Upgrade('Hard Worker', ['Ten Thunders', 'Arcanist'], ['Upgrade', 'Foundry', 'Rare 1'], 1),
		new Upgrade('The Rising Sun', ['Ten Thunders', 'Neverborn'], ['Upgrade', 'Jacob Lynch', 'Limited'], 2),
		new Upgrade('Expert Cheater', ['Ten Thunders', 'Neverborn'], ['Upgrade', 'Jacob Lynch'], 2),
		new Upgrade('Endless Hunger', ['Ten Thunders', 'Neverborn'], ['Upgrade', 'Jacob Lynch', 'Limited'], 2),
		new Upgrade('Wanna See a Trick', ['Ten Thunders', 'Neverborn'], ['Upgrade', 'Jacob Lynch'], 1),
		new Upgrade('Woke Up With a Hand', ['Ten Thunders', 'Neverborn'], ['Upgrade', 'Jacob Lynch'], 2),
		new Upgrade('Addict', ['Ten Thunders', 'Neverborn'], ['Upgrade', 'Jacob Lynch', 'Hungering Darkness', 'Rare 1'], 1)
	]
};