/*globals C, Upgrade */
/*exported UpgradeList */
var UpgradeList = {
	data: [
		new Upgrade('Plant Evidence', [C.Guild], [C.Upgrade, C.Rare3, C.Wave1], 1),
		new Upgrade('Vengeance Bullet', [C.Guild], [C.Upgrade, C.Master, C.Henchman, C.Rare1, C.Wave1], 1),
		new Upgrade('Lead Lined Coat', [C.Guild], [C.Upgrade, C.Henchman, C.Enforcer, C.Living, C.Rare3, C.Wave1], 2),
		new Upgrade('The Thalarian Stone', [C.Guild], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Badge of Office', [C.Guild], [C.Upgrade, C.Leader, C.Limited, C.Wave1], 2),
		new Upgrade('Implacable', [C.Guild], [C.Upgrade, 'Lady Justice', C.Wave1], 1),
		new Upgrade('Justice Unleashed', [C.Guild], [C.Upgrade, 'Lady Justice', C.Wave1], 1),
		new Upgrade('Last Stand', [C.Guild], [C.Upgrade, 'Lady Justice', C.Wave1], 1),
		new Upgrade('Vendetta', [C.Guild], [C.Upgrade, 'Lady Justice', C.Limited, C.Wave1], 2),
		new Upgrade('Unrelenting Leader', [C.Guild], [C.Upgrade, 'The Judge', C.Wave1], 2),
		new Upgrade('Flames of the Pit', [C.Guild], [C.Upgrade, C.GuildMarshal, C.Rare1, C.Wave1], 2),
		new Upgrade('Cherufe\'s Imprint', [C.Guild], [C.Upgrade, 'Sonnia', C.Wave1], 1),
		new Upgrade('Reincarnation', [C.Guild], [C.Upgrade, 'Sonnia', C.Limited, C.Wave1], 1),
		new Upgrade('The Mask', [C.Guild], [C.Upgrade, 'Sonnia', C.Wave1], 1),
		new Upgrade('Counterspell Aura', [C.Guild], [C.Upgrade, 'Sonnia', C.Wave1], 1),
		new Upgrade('Witch Hunt', [C.Guild], [C.Upgrade, 'Samael Hopkins', C.Wave1], 2),
		new Upgrade('Disrupt Magic', [C.Guild], [C.Upgrade, C.WitchHunter, C.Rare1, C.Wave1], 2),
		new Upgrade('Os Veo', [C.Guild], [C.Upgrade, 'Perdita', C.Wave1], 2),
		new Upgrade('Trick Shooting', [C.Guild], [C.Upgrade, 'Perdita', C.Wave1], 2),
		new Upgrade('Aura Ancestral', [C.Guild], [C.Upgrade, 'Perdita', C.Wave1], 1),
		new Upgrade('Tormenta de Plomo', [C.Guild], [C.Upgrade, C.Family, C.Rare1, C.Wave1], 1),
		new Upgrade('Diestro', [C.Guild], [C.Upgrade, C.Family, C.Rare1, C.Wave1], 3),
		new Upgrade('Hermanos De Armas', [C.Guild], [C.Upgrade, C.Family, C.Rare1, C.Wave1], 1),
		new Upgrade('Wade In', [C.Guild], [C.Upgrade, 'Franscisco Ortega', C.Wave1], 1),
		
		new Upgrade('Arcanist Assets', [C.Guild], [C.Upgrade, 'C. Hoffman', C.Wave2], 1),
		new Upgrade('On Site Assimiliation', [C.Guild], [C.Upgrade, 'C. Hoffman', C.Wave2], 2),
		new Upgrade('Field Mechanic', [C.Guild], [C.Upgrade, 'C. Hoffman', C.Limited, C.Wave2], 2),
		new Upgrade('Remote Mines', [C.Guild], [C.Upgrade, 'C. Hoffman', C.Wave2], 2),
		new Upgrade('Patchwork Plating', [C.Guild], [C.Upgrade, C.Modification, C.Wave2], 0),
		new Upgrade('Programmed Directive', [C.Guild], [C.Upgrade, C.Modification, C.Wave2], 0),
		new Upgrade('Hydraulics', [C.Guild], [C.Upgrade, C.Modification, C.Wave2], 0),
		new Upgrade('Targeting Systems', [C.Guild], [C.Upgrade, C.Modification, C.Wave2], 0),
		new Upgrade('Pieces of Myself', [C.Guild], [C.Upgrade, 'Ryle', C.Wave2], 1),
		new Upgrade('Tessellating Magnet', [C.Guild], [C.Upgrade, C.Construct, C.Wave2], 1),
		new Upgrade('Surprisingly Loyal', [C.Guild, C.Neverborn], [C.Upgrade, 'Lucius', C.Wave2], 1),
		new Upgrade('Secret Objectives', [C.Guild, C.Neverborn], [C.Upgrade, 'Lucius', C.Wave2], 1),
		new Upgrade('Legalese', [C.Guild, C.Neverborn], [C.Upgrade, 'Lucius', C.Wave2], 1),
		new Upgrade('Secret Assets', [C.Guild, C.Neverborn], [C.Upgrade, 'Lucius', C.Wave2], 2),
		new Upgrade('Watch my Back', [C.Guild], [C.Upgrade, 'Lucius', C.Guardsman, C.Rare1, C.Wave2], 2),
		new Upgrade('Useless Duplications', [C.Guild, C.Neverborn], [C.Upgrade, C.Mimic, C.Rare1, C.Wave2], 1),
		new Upgrade('Dampening Field', [C.Guild], [C.Upgrade, C.Henchman, C.Master, C.Rare1, C.Wave2], 1),
		new Upgrade('Expert Sleuth', [C.Guild], [C.Upgrade, C.Rare3, C.Wave2], 1),
				
		new Upgrade('Unnerving Aura', [C.Resurrectionist], [C.Upgrade, C.Rare3, C.Wave1], 1),
		new Upgrade('Decaying Aura', [C.Resurrectionist], [C.Upgrade, C.Rare1, C.Wave1], 2),
		new Upgrade('Transfusion', [C.Resurrectionist], [C.Upgrade, C.Rare2, C.Wave1], 1),
		new Upgrade('Maniacal Laugh', [C.Resurrectionist], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Corpse Bloat', [C.Resurrectionist], [C.Upgrade, C.Master, C.Henchman, C.Rare1, C.Wave1], 2),
		new Upgrade('Asylum Stone', [C.Resurrectionist], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Sinister Reputation', [C.Resurrectionist], [C.Upgrade, 'Seamus', C.Limited, C.Wave1], 1),
		new Upgrade('Red Chapel Killer', [C.Resurrectionist], [C.Upgrade, 'Seamus', C.Wave1], 1),
		new Upgrade('Not Too Banged Up', [C.Resurrectionist], [C.Upgrade, 'Seamus', 'Madam Sybelle', C.Rare1, C.Wave1], 1),
		new Upgrade('Bag O\' Tools', [C.Resurrectionist], [C.Upgrade, 'Seamus', C.Limited, C.Wave1], 1),
		new Upgrade('Mad Haberdasher', [C.Resurrectionist], [C.Upgrade, 'Seamus', C.Wave1], 2),
		new Upgrade('Bleeding Tongue', [C.Resurrectionist], [C.Upgrade, 'Madame Sybelle', C.Wave1], 1),
		new Upgrade('Plastic Surgery', [C.Resurrectionist, C.Guild], [C.Upgrade, 'McMourning', C.Wave1], 1),
		new Upgrade('Evidence Tampering', [C.Resurrectionist, C.Guild], [C.Upgrade, 'McMourning', C.Wave1], 2),
		new Upgrade('Moonlighting', [C.Resurrectionist], [C.Upgrade, 'McMourning', C.Wave1], 1),
		new Upgrade('On the Clock', [C.Guild], [C.Upgrade, 'McMourning', C.Wave1], 1),
		new Upgrade('Unknowable Pain', [C.Resurrectionist, C.Guild], [C.Upgrade, 'McMourning', 'Sebastian', C.Rare1, C.Wave1], 1),
		new Upgrade('Those Are Not Ours!', [C.Resurrectionist], [C.Upgrade, 'Sebastian', C.Wave1], 1),
		new Upgrade('Undertaker', [C.Resurrectionist], [C.Upgrade, 'Nicodem', C.Wave1], 1),
		new Upgrade('Reaper Grin', [C.Resurrectionist], [C.Upgrade, 'Nicodem', C.Wave1], 1),
		new Upgrade('Shadow Embrace', [C.Resurrectionist], [C.Upgrade, 'Nicodem', C.Wave1], 1),
		new Upgrade('Necrotic King', [C.Resurrectionist], [C.Upgrade, 'Nicodem', C.Wave1], 2),
		new Upgrade('My Favorite Shovel', [C.Resurrectionist], [C.Upgrade, 'Mortimer', C.Wave1], 2),
		new Upgrade('Love Thy Master', [C.Resurrectionist], [C.Upgrade, 'Nicodem', 'Mortimer', C.Rare1, C.Wave1], 1),
		
		new Upgrade('Spare Parts', [C.Resurrectionist], [C.Upgrade, C.Leader, C.Wave2], 2),
		new Upgrade('Forgotten Path', [C.Resurrectionist], [C.Upgrade, 'Molly', C.Limited, C.Wave2], 1),
		new Upgrade('Forgotten Life', [C.Resurrectionist], [C.Upgrade, 'Molly', C.Limited, C.Wave2], 1),
		new Upgrade('Terrible Knowledge', [C.Resurrectionist], [C.Upgrade, 'Molly', C.Wave2], 1),
		new Upgrade('Tear of the Gorgon', [C.Resurrectionist], [C.Upgrade, 'Molly', C.Wave2], 3),
		new Upgrade('Pack', [C.Resurrectionist], [C.Upgrade, 'Rogue Necromancy', C.Wave2], 1),
		new Upgrade('Take Back the Night', [C.Resurrectionist], [C.Upgrade, C.Horror, C.Rare1, C.Wave2], 1),
		new Upgrade('Spirit Whispers', [C.Resurrectionist], [C.Upgrade, 'Datsue Ba', C.Wave2], 1),
		new Upgrade('Absorb Spirit', [C.Resurrectionist], [C.Upgrade, 'Kirai', C.Wave2], 1),
		new Upgrade('Bloody Shears', [C.Resurrectionist], [C.Upgrade, 'Kirai', C.Limited, C.Wave2], 1),
		new Upgrade('Unforgiven', [C.Resurrectionist], [C.Upgrade, 'Kirai', C.Limited, C.Wave2], 2),
		new Upgrade('Swirling Aether', [C.Resurrectionist], [C.Upgrade, 'Kirai', C.Wave2], 2),
		new Upgrade('Spirit Beacon', [C.Resurrectionist], [C.Upgrade, 'Kirai', C.Spirit, C.Rare1, C.Wave2], 1),
		new Upgrade('Spare Parts', [C.Resurrectionist], [C.Upgrade, C.Leader, C.Wave2], 2),
		new Upgrade('Necrotic Preparation', [C.Resurrectionist], [C.Upgrade, C.Rare3, C.Wave2], 1),
		new Upgrade('Pack', [C.Resurrectionist], [C.Upgrade, 'Rogue Necromancy', C.Wave2], 1),
		
		new Upgrade('Imbued Protection', [C.Arcanist], [C.Upgrade, C.Rare2, C.Wave1], 2),
		new Upgrade('Imbued Energies', [C.Arcanist], [C.Upgrade, C.Rare3, C.Wave1], 1),
		new Upgrade('The Philosopher\'s Stone', [C.Arcanist], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Arcane Reservoir', [C.Arcanist], [C.Upgrade, C.Leader, C.Wave1], 2),
		new Upgrade('Recharge Soulstone', [C.Arcanist], [C.Upgrade, C.Master, C.Henchman, C.Rare2, C.Wave1], 1),
		new Upgrade('December\'s Pawn', [C.Arcanist], [C.Upgrade, 'Rasputina', C.Wave1], 2),
		new Upgrade('Cold Nights', [C.Arcanist], [C.Upgrade, 'Rasputina', C.Wave1], 1),
		new Upgrade('Child of December', [C.Arcanist], [C.Upgrade, 'Rasputina', C.Wave1], 1),
		new Upgrade('Shattered Heart', [C.Arcanist], [C.Upgrade, 'Rasputina', C.Limited, C.Wave1], 3),
		new Upgrade('Armor of December', [C.Arcanist], [C.Upgrade, C.FrozenHeart, C.Limited, C.Rare2, C.Wave1], 1),
		new Upgrade('Sub Zero', [C.Arcanist], [C.Upgrade, C.FrozenHeart, C.Rare1, C.Wave1], 1),
		new Upgrade('Feral Instinct', [C.Arcanist], [C.Upgrade, 'Marcus', C.Wave1], 1),
		new Upgrade('The Hunger Cry', [C.Arcanist], [C.Upgrade, 'Marcus', C.Wave1], 1),
		new Upgrade('The Trail of the Gods', [C.Arcanist], [C.Upgrade, 'Marcus', C.Limited, C.Wave1], 1),
		new Upgrade('The God\'s Domain', [C.Arcanist], [C.Upgrade, 'Marcus', C.Limited, C.Wave1], 1),
		new Upgrade('Skinwalker', [C.Arcanist], [C.Upgrade, 'Myranda', C.Wave1], 1),
		new Upgrade('Pack Leader', [C.Arcanist], [C.Upgrade, C.Beast, C.Rare1, C.Wave1], 1),
		new Upgrade('Field Generator', [C.Arcanist], [C.Upgrade, 'Ramos', C.Wave1], 2),
		new Upgrade('Combat Mechanic', [C.Arcanist], [C.Upgrade, 'Ramos', C.Wave1], 2),
		new Upgrade('Electric Summoning', [C.Arcanist], [C.Upgrade, 'Ramos', C.Wave1], 1),
		new Upgrade('Under Pressure', [C.Arcanist], [C.Upgrade, 'Ramos', C.Wave1], 2),
		new Upgrade('Open Current', [C.Arcanist], [C.Upgrade, 'Joss', C.Wave1], 1),
		new Upgrade('Bleeding Edge Tech', [C.Arcanist], [C.Upgrade, C.Msu, C.Rare1, C.Wave1], 1),
		
		new Upgrade('Grab and Drop', [C.Arcanist], [C.Upgrade, 'Kaeris', C.Limited, C.Wave2], 1),
		new Upgrade('Purifying Fire', [C.Arcanist], [C.Upgrade, 'Kaeris', C.Limited, C.Wave2], 1),
		new Upgrade('Born of Fire', [C.Arcanist], [C.Upgrade, 'Kaeris', C.Wave2], 2),
		new Upgrade('Blinding Flame', [C.Arcanist], [C.Upgrade, 'Kaeris', C.Wave2], 1),
		new Upgrade('Powered by Flame', [C.Arcanist], [C.Upgrade, C.Msu, C.Rare1, C.Wave2], 2),
		new Upgrade('Patron\'s Blessing', [C.Arcanist], [C.Upgrade, 'The Captain', C.Wave2], 2),
		new Upgrade('Cabaret Choreography', [C.Arcanist], [C.Upgrade, 'Colette', C.Wave2], 2),
		new Upgrade('A Ladys Secret', [C.Arcanist], [C.Upgrade, 'Colette', C.Wave2], 2),
		new Upgrade('Nothing Up My Sleeve', [C.Arcanist], [C.Upgrade, 'Colette', C.Wave2], 1),
		new Upgrade('Shell Game', [C.Arcanist], [C.Upgrade, 'Colette', C.Wave2], 1),
		new Upgrade('Practiced Production', [C.Arcanist], [C.Upgrade, C.Showgirl, C.Wave2], 1),
		new Upgrade('Smoke and Mirrors', [C.Arcanist], [C.Upgrade, 'Cassandra', C.Wave2], 1),
		new Upgrade('Challenge the Crowd', [C.Arcanist], [C.Upgrade, 'Ironsides', C.Wave2], 1),
		new Upgrade('Iron Determination', [C.Arcanist], [C.Upgrade, 'Ironsides', C.Wave2], 1),
		new Upgrade('Frontline Leadership', [C.Arcanist], [C.Upgrade, 'Ironsides', C.Wave2], 2),
		new Upgrade('Warding Runes', [C.Arcanist], [C.Upgrade, 'Ironsides', C.Henchman, C.Limited, C.Rare2, C.Wave2], 1),
		new Upgrade('Message from the Union', [C.Arcanist], [C.Upgrade, 'Ironsides', C.Wave2], 1),
		new Upgrade('Nemesis Ward', [C.Arcanist], [C.Upgrade, 'Oxfordian Mage', C.Rare1, C.Wave2], 0),
		new Upgrade('Blood Ward', [C.Arcanist], [C.Upgrade, 'Oxfordian Mage', C.Rare1, C.Wave2], 0),
		new Upgrade('Doom Ward', [C.Arcanist], [C.Upgrade, 'Oxfordian Mage', C.Rare1, C.Wave2], 0),
		new Upgrade('Seize the Day', [C.Arcanist], [C.Upgrade, C.Leader, C.Wave2], 1),
		new Upgrade('Killswitch', [C.Arcanist], [C.Upgrade, C.Rare1, C.Wave2], 1),
		new Upgrade('Decoy', [C.Arcanist], [C.Upgrade, C.Rare2, C.Wave2], 0),
				
		new Upgrade('Pact', [C.Neverborn], [C.Upgrade, C.Rare3, C.Wave1], 1),
		new Upgrade('Fears Given Form', [C.Neverborn], [C.Upgrade, C.Master, C.Henchman, C.Rare2, C.Wave1], 1),
		new Upgrade('Nexus of Power', [C.Neverborn], [C.Upgrade, C.Henchman, C.Enforcer, C.Rare1, C.Wave1], 1),
		new Upgrade('Stone of Tyrant Echoes', [C.Neverborn], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Aether Conections', [C.Neverborn], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Beckon Malifaux', [C.Neverborn], [C.Upgrade, 'Lilith', C.Wave1], 1),
		new Upgrade('Living Blade', [C.Neverborn], [C.Upgrade, 'Lilith', C.Wave1], 2),
		new Upgrade('Wicked Mistress', [C.Neverborn], [C.Upgrade, 'Lilith', C.Wave1], 1),
		new Upgrade('Summon the Blood', [C.Neverborn], [C.Upgrade, 'Lilith', C.Wave1], 1),
		new Upgrade('Nephilim Gladiatus', [C.Neverborn], [C.Upgrade, 'Barbaros', C.Wave1], 1),
		new Upgrade('Obsidian Talons', [C.Neverborn], [C.Upgrade, C.Nephilim, C.Rare1, C.Wave1], 1),
		new Upgrade('Rapid Growth', [C.Neverborn], [C.Upgrade, C.Nephilim, C.Rare1, C.Wave1], 1),
		new Upgrade('Fugue State', [C.Neverborn], [C.Upgrade, 'Pandora', C.Wave1], 2),
		new Upgrade('Cry for Me', [C.Neverborn], [C.Upgrade, 'Pandora', C.Wave1], 2),
		new Upgrade('The Box Opens', [C.Neverborn], [C.Upgrade, 'Pandora', C.Limited, C.Wave1], 2),
		new Upgrade('Voices', [C.Neverborn], [C.Upgrade, 'Pandora', C.Limited, C.Wave1], 1),
		new Upgrade('Depression', [C.Neverborn], [C.Upgrade, C.Woe, C.Rare1, C.Wave1], 1),
		new Upgrade('Best Behavior', [C.Neverborn], [C.Upgrade, 'Candy', C.Wave1], 1),
		new Upgrade('Animal Shape', [C.Neverborn, C.Gremlin], [C.Upgrade, 'Zoraida', C.Limited, C.Wave1], 2),
		new Upgrade('Crystal Ball', [C.Neverborn, C.Gremlin], [C.Upgrade, 'Zoraida', C.Limited, C.Wave1], 2),
		new Upgrade('Tarot Reading', [C.Neverborn, C.Gremlin], [C.Upgrade, 'Zoraida', C.Wave1], 2),
		new Upgrade('Hex Bag', [C.Neverborn, C.Gremlin], [C.Upgrade, 'Zoraida', C.Wave1], 1),
		new Upgrade('Eternal Fiend', [C.Neverborn], [C.Upgrade, 'Bad Juju', C.Wave1], 2),
		new Upgrade('Hexed Among You', [C.Neverborn, C.Gremlin], [C.Upgrade, C.Swampfiend, C.Rare1, C.Wave1], 1),
		
		new Upgrade('Otherworldly', [C.Neverborn], [C.Upgrade, 'The Dreamer', C.Wave2], 2),
		new Upgrade('Restless Dreams', [C.Neverborn], [C.Upgrade, 'The Dreamer', C.Limited, C.Wave2], 1),
		new Upgrade('Tantrum', [C.Neverborn], [C.Upgrade, 'The Dreamer', C.Wave2], 2),
		new Upgrade('Dreams of Pain', [C.Neverborn], [C.Upgrade, 'The Dreamer', C.Limited, C.Rare1, C.Wave2], 5),
		new Upgrade('On Dreaming Wings', [C.Neverborn], [C.Upgrade, 'The Dreamer', C.Nightmare, C.Wave2], 2),
		new Upgrade('Handbag', [C.Neverborn], [C.Upgrade, 'Widow Weaver', C.Wave2], 2),
		new Upgrade('The True Mother', [C.Neverborn], [C.Upgrade, 'Nekima', C.Wave2], 2),
		new Upgrade('Threads of Fate', [C.Neverborn], [C.Upgrade, 'Collodi', C.Wave2], 1),
		new Upgrade('Fated', [C.Neverborn], [C.Upgrade, 'Collodi', C.Limited, C.Wave2], 1),
		new Upgrade('Breathe Life', [C.Neverborn], [C.Upgrade, 'Collodi', C.Wave2], 1),
		new Upgrade('Bag of Props', [C.Neverborn], [C.Upgrade, 'Collodi', C.Limited, C.Wave2], 1),
		new Upgrade('A Friend To Talk To', [C.Neverborn], [C.Upgrade, 'Vasilisa', C.Wave2], 2),
		new Upgrade('Strum the Threads', [C.Neverborn], [C.Upgrade, 'Collodi', 'Vasilisa', C.Rare1, C.Wave2], 1),
		new Upgrade('Protect the Young', [C.Neverborn], [C.Upgrade, 'Spawn Mother', C.Wave2], 1),
		new Upgrade('Retributions Eye', [C.Neverborn], [C.Upgrade, C.Enforcer, C.Rare1, C.Wave2], 1),
		new Upgrade('On Wings of Darkness', [C.Neverborn], [C.Upgrade, C.Leader, C.Wave2], 1),
		new Upgrade('The Mimic\'s Blessing', [C.Neverborn], [C.Upgrade, C.NonMaster, C.Rare3, C.Wave2], 1),
				
		new Upgrade('Scramble', [C.Outcast], [C.Upgrade, C.Limited, C.Rare3, C.Wave1], 2),
		new Upgrade('Tally Sheet', [C.Outcast], [C.Upgrade, C.Master, C.Henchman, C.Rare2, C.Wave1], 1),
		new Upgrade('The Traveler\'s Stone', [C.Outcast], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Survivivalist', [C.Outcast], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Oath Keeper', [C.Outcast], [C.Upgrade, C.Rare3, C.Wave1], 1),
		new Upgrade('Paid in Blood', [C.Outcast], [C.Upgrade, 'Von Schill', C.Wave1], 2),
		new Upgrade('Engage at Will', [C.Outcast], [C.Upgrade, 'Von Schill', C.Wave1], 1),
		new Upgrade('The Shirt Comes Off', [C.Outcast], [C.Upgrade, 'Von Schill', C.Wave1], 1),
		new Upgrade('Ancient Tomes', [C.Outcast], [C.Upgrade, 'Hannah', C.Wave1], 2),
		new Upgrade('Spoils of War', [C.Outcast], [C.Upgrade, C.Freikorps, C.Master, C.Henchman, C.Rare1, C.Wave1], 1),
		new Upgrade('Eternal Journey', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Tara', C.Wave1], 1),
		new Upgrade('Knowledge of Eternity', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Tara', C.Wave1], 2),
		new Upgrade('Obliteration Symbiote', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Tara', C.Wave1], 2),
		new Upgrade('Dead of Winters', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Tara', C.Wave1], 1),
		new Upgrade('Voiceless Words', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Nothing Beast', 'Tara', C.Rare1, C.Wave1], 1),
		new Upgrade('Long Forgotten Magics', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Karina', C.Wave1], 1),
		new Upgrade('Sisters in Spirit', [C.Outcast], [C.Upgrade, C.Sister, C.Rare1, C.Wave1], 1),
		new Upgrade('Sisters in Fury', [C.Outcast], [C.Upgrade, 'Viktoria of Blood', 'Viktoria of Ash', C.Rare1, C.Wave1], 2),
		new Upgrade('Howling Wolf Tattoo', [C.Outcast], [C.Upgrade, C.Sister, C.Rare1, C.Wave1], 1),
		new Upgrade('Mark of Shez\'uul', [C.Outcast], [C.Upgrade, C.Sister, C.Rare1, C.Wave1], 2),
		new Upgrade('Synchronized Slaying', [C.Outcast], [C.Upgrade, C.Sister, C.Rare1, C.Wave1], 2),
		
		new Upgrade('Firing Squad Injustice', [C.Outcast], [C.Upgrade, 'Jack Daw', C.Cursed, C.Wave2], 0),
		new Upgrade('Drowning Injustice', [C.Outcast], [C.Upgrade, 'Jack Daw', C.Cursed, C.Wave2], 0),
		new Upgrade('Guillotine Injustice', [C.Outcast], [C.Upgrade, 'Jack Daw', C.Cursed, C.Wave2], 0),
		new Upgrade('Betrayer', [C.Outcast], [C.Upgrade, 'Jack Daw', C.Wave2], 1),
		new Upgrade('Writhing Torment', [C.Outcast], [C.Upgrade, 'Jack Daw', C.Wave2], 2),
		new Upgrade('Twist and Turn', [C.Outcast], [C.Upgrade, 'Jack Daw', C.Limited, C.Wave2], 2),
		new Upgrade('The Creeping Terror', [C.Outcast], [C.Upgrade, C.Tormented, C.Rare1, C.Wave2], 1),
		new Upgrade('Fearful Whispers', [C.Outcast], [C.Upgrade, 'Montresor', C.Wave2], 1),
		new Upgrade('The Plague', [C.Outcast], [C.Upgrade, 'Hamelin', C.Wave2], 2),
		new Upgrade('The Piper', [C.Outcast], [C.Upgrade, 'Hamelin', C.Limited, C.Wave2], 2),
		new Upgrade('Tools of the Tyrant', [C.Outcast], [C.Upgrade, 'Hamelin', C.Wave2], 2),
		new Upgrade('Sewer King', [C.Outcast], [C.Upgrade, 'Hamelin', C.Wave2], 1),
		new Upgrade('Hollow', [C.Outcast], [C.Upgrade, 'Nix', C.Wave2], 2),
		new Upgrade('Infectious Melodies', [C.Outcast], [C.Upgrade, C.Nihilist, C.Rare1, C.Wave2], 1),
		new Upgrade('Pariah of Bone', [C.Outcast], [C.Upgrade, 'Leveticus', C.Limited, C.Wave2], 1),
		new Upgrade('To the Earth Return', [C.Outcast], [C.Upgrade, 'Leveticus', C.Wave2], 1),
		new Upgrade('Pariah of Iron', [C.Outcast], [C.Upgrade, 'Leveticus', C.Limited, C.Wave2], 1),
		new Upgrade('From the Aether', [C.Outcast], [C.Upgrade, 'Rusty Alyce', C.Wave2], 2),
		new Upgrade('Desolate Soul', [C.Outcast], [C.Upgrade, 'Leveticus', 'Rusty Alyce', C.Wave2], 2),
		new Upgrade('From Ash', [C.Outcast], [C.Upgrade, 'Leveticus', C.Wave2], 2),
		new Upgrade('I Pay Better', [C.Outcast], [C.Upgrade, C.Master, C.Henchman, C.Rare1, C.Wave2], 1),
		new Upgrade('Scout the Field', [C.Outcast], [C.Upgrade, C.Rare3, C.Wave2], 1),
		new Upgrade('Void Shield', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Nothing Beast', C.Wave2], 0),
		new Upgrade('The Faces of Oblivion', [C.Outcast, C.Resurrectionist], [C.Upgrade, 'Karina', C.Wave2], 0),
		
		new Upgrade('Liquid Bravery', [C.Gremlin], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Quality Mash Liquor', [C.Gremlin], [C.Upgrade, C.Master, C.Henchman, C.Rare1, C.Wave1], 2),
		new Upgrade('Dirty Cheater', [C.Gremlin], [C.Upgrade, C.Rare2, C.Wave1], 1),
		new Upgrade('The Guardian Stone', [C.Gremlin], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Show Off', [C.Gremlin], [C.Upgrade, C.Gremlin, C.Rare1, C.Wave1], 1),
		new Upgrade('Stilts', [C.Gremlin], [C.Upgrade, C.Gremlin, C.Rare1, C.Wave1], 1),
		new Upgrade('Pig Feed', [C.Gremlin], [C.Upgrade, 'Somer', C.Wave1], 1),
		new Upgrade('Family Tree', [C.Gremlin], [C.Upgrade, 'Somer', C.Wave1], 2),
		new Upgrade('Can \'o Beans', [C.Gremlin], [C.Upgrade, 'Somer', C.Wave1], 1),
		new Upgrade('Encouragement', [C.Gremlin], [C.Upgrade, 'Somer', C.Wave1], 2),
		new Upgrade('I\'ll Love It and Pet it...', [C.Gremlin], [C.Upgrade, 'Lenny', C.Wave1], 1),
		new Upgrade('Binge', [C.Gremlin, C.TenThunders], [C.Upgrade, 'The Brewmaster', C.Wave1], 1),
		new Upgrade('Hold Their Hari Back', [C.Gremlin, C.TenThunders], [C.Upgrade, 'The Brewmaster', C.Wave1], 1),
		new Upgrade('Running Tab', [C.Gremlin, C.TenThunders], [C.Upgrade, 'The Brewmaster', C.Wave1], 2),
		new Upgrade('The Good Stuff', [C.Gremlin, C.TenThunders], [C.Upgrade, 'The Brewmaster', C.Wave1], 1),
		new Upgrade('Drinking "Problem"', [C.Gremlin, C.TenThunders], [C.Upgrade, 'Tri\'chi', C.Rare1, C.Wave1], 1),
		new Upgrade('Angry Drunk', [C.Gremlin, C.TenThunders], [C.Upgrade, 'Whiskey Golem', C.Wave1], 2),
		new Upgrade('Hooch Igniter', [C.Gremlin], [C.Upgrade, 'Ophelia', C.Wave1], 1),
		new Upgrade('Jug Rocket', [C.Gremlin], [C.Upgrade, 'Ophelia', C.Wave1], 1),
		new Upgrade('My Threatenin\' Gun', [C.Gremlin], [C.Upgrade, 'Ophelia', C.Wave1], 1),
		new Upgrade('Gremlin-See', [C.Gremlin], [C.Upgrade, C.Kin, C.Rare2, C.Wave1], 1),
		new Upgrade('Team Work', [C.Gremlin], [C.Upgrade, C.Kin, C.Rare3, C.Wave1], 1),
		
		new Upgrade('Clobberin\' Stick', [C.Gremlin], [C.Upgrade, 'Ulix', C.Wave2], 1),
		new Upgrade('Huntin\' Bow', [C.Gremlin], [C.Upgrade, 'Ulix', C.Wave2], 2),
		new Upgrade('Pig Sling', [C.Gremlin], [C.Upgrade, 'Ulix', C.Wave2], 1),
		new Upgrade('Husbandry', [C.Gremlin], [C.Upgrade, 'Ulix', C.Wave2], 3),
		new Upgrade('Saddle', [C.Gremlin], [C.Upgrade, 'Old Major', 'Gracie', C.Rare1, C.Wave2], 1),
		new Upgrade('Corn Husks', [C.Gremlin], [C.Upgrade, 'Ulix', C.Pig, C.Wave2], 2),
		new Upgrade('Three Demon Bag', [C.Gremlin], [C.Upgrade, 'Wong', C.Wave2], 2),
		new Upgrade('A Gremlin\'s Luck', [C.Gremlin], [C.Upgrade, 'Wong', C.Limited, C.Wave2], 1),
		new Upgrade('Ooo Glowy', [C.Gremlin], [C.Upgrade, 'Wong', C.Limited, C.Wave2], 1),
		new Upgrade('Explosive Solutions', [C.Gremlin], [C.Upgrade, 'Wong', C.Wave2], 2),
		new Upgrade('Mud Toss', [C.Gremlin], [C.Upgrade, 'McTavish', 'Mancha Roja', C.Rare1, C.Wave2], 1),
		new Upgrade('Extra Gremlin', [C.Gremlin], [C.Upgrade, 'Mancha Roja', C.Wave2], 2),
		new Upgrade('Bounty', [C.Gremlin], [C.Upgrade, 'Mah Tucket', 'Trixiebelle', C.Rare1, C.Wave2], 1),
		new Upgrade('Out for Blood', [C.Gremlin], [C.Upgrade, 'Mah Tucket', C.Wave2], 2),
		new Upgrade('Know the Terrain', [C.Gremlin], [C.Upgrade, 'Mah Tucket', C.Wave2], 1),
		new Upgrade('Lead Lined Apron', [C.Gremlin], [C.Upgrade, 'Mah Tucket', C.Wave2], 2),
		new Upgrade('Cute Critters', [C.Gremlin], [C.Upgrade, 'McTavish', C.Wave2], 1),
		new Upgrade('A Gun For A Lady', [C.Gremlin], [C.Upgrade, 'Trixiebelle', C.Wave2], 1),
		new Upgrade('Hexed Among You', [C.Gremlin, C.Neverborn], [C.Upgrade, C.Swampfiend, C.Wave2], 1),
		new Upgrade('On Yer Toes', [C.Gremlin], [C.Upgrade, C.Master, C.Henchman, C.Rare1, C.Wave2], 1),
		new Upgrade('Hide in the Mud', [C.Gremlin], [C.Upgrade, C.Rare3, C.Wave2], 1),
		
		new Upgrade('Servent of 5 Dragons', [C.TenThunders], [C.Upgrade, C.Rare3, C.Wave1], 1),
		new Upgrade('Broken Promises', [C.TenThunders], [C.Upgrade, C.Master, C.Henchman, C.Rare2, C.Wave1], 2),
		new Upgrade('Recalled Training', [C.TenThunders], [C.Upgrade, C.Master, C.Henchman, C.Rare3, C.Wave1], 1),
		new Upgrade('Dragon Stone', [C.TenThunders], [C.Upgrade, C.Leader, C.Wave1], 1),
		new Upgrade('Misdirection', [C.TenThunders], [C.Upgrade, C.Leader, C.Wave1], 2),
		new Upgrade('Disguise', [C.TenThunders, C.Outcast], [C.Upgrade, 'Misaki', C.Limited, C.Wave1], 2),
		new Upgrade('Cutpurse', [C.TenThunders, C.Outcast], [C.Upgrade, 'Misaki', C.Wave1], 1),
		new Upgrade('Untouchable', [C.TenThunders, C.Outcast], [C.Upgrade, 'Misaki', C.Wave1], 1),
		new Upgrade('Stalking Bisento', [C.TenThunders, C.Outcast], [C.Upgrade, 'Misaki', C.Limited, C.Wave1], 2),
		new Upgrade('Smoke & Shadows', [C.TenThunders, C.Outcast], [C.Upgrade, C.LastBlossom, C.Rare1, C.Wave1], 1),
		new Upgrade('Call the Thunder', [C.TenThunders], [C.Upgrade, 'Ototo', C.Wave1], 1),
		new Upgrade('Thunderous Smash', [C.TenThunders, C.Arcanist], [C.Upgrade, 'Mei Feng', C.Wave1], 1),
		new Upgrade('Seismic Claws', [C.TenThunders, C.Arcanist], [C.Upgrade, 'Mei Feng', C.Wave1], 1),
		new Upgrade('Price of Progress', [C.TenThunders, C.Arcanist], [C.Upgrade, 'Mei Feng', C.Wave1], 1),
		new Upgrade('Vapormancy', [C.TenThunders, C.Arcanist], [C.Upgrade, 'Mei Feng', C.Wave1], 1),
		new Upgrade('People\'s Challenge', [C.TenThunders, C.Arcanist], [C.Upgrade, 'Kang', C.Wave1], 2),
		new Upgrade('Hard Worker', [C.TenThunders, C.Arcanist], [C.Upgrade, C.Foundry, C.Rare1, C.Wave1], 1),
		new Upgrade('The Rising Sun', [C.TenThunders, C.Neverborn], [C.Upgrade, 'Jacob Lynch', C.Limited, C.Wave1], 2),
		new Upgrade('Expert Cheater', [C.TenThunders, C.Neverborn], [C.Upgrade, 'Jacob Lynch', C.Wave1], 2),
		new Upgrade('Endless Hunger', [C.TenThunders, C.Neverborn], [C.Upgrade, 'Jacob Lynch', C.Limited, C.Wave1], 2),
		new Upgrade('Wanna See a Trick', [C.TenThunders, C.Neverborn], [C.Upgrade, 'Jacob Lynch', C.Wave1], 1),
		new Upgrade('Woke Up With a Hand', [C.TenThunders, C.Neverborn], [C.Upgrade, 'Jacob Lynch', C.Wave1], 2),
		new Upgrade('Addict', [C.TenThunders, C.Neverborn], [C.Upgrade, 'Jacob Lynch', 'Hungering Darkness', C.Rare1, C.Wave1], 1),
		
		new Upgrade('Badge of Speed', [C.TenThunders, C.Guild], [C.Upgrade, 'Lucas McCabe', C.Wave2], 2),
		new Upgrade('Glowing Sabre', [C.TenThunders, C.Guild], [C.Upgrade, 'Lucas McCabe', C.Wave2], 2),
		new Upgrade('Elixir of Life', [C.TenThunders, C.Guild], [C.Upgrade, 'Lucas McCabe', C.Wave2], 2),
		new Upgrade('Strangemetal Shirt', [C.TenThunders, C.Guild], [C.Upgrade, 'Lucas McCabe', C.Wave2], 1),
		new Upgrade('Barbs', [C.TenThunders, C.Guild], [C.Upgrade, 'Lucas McCabe', C.Wave2], 1),
		new Upgrade('Promises', [C.TenThunders, C.Guild], [C.Upgrade, C.BlackSheep, C.Rare1, C.Wave2], 1),
		new Upgrade('Fortify the Spirit', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Yan Lo', C.Wave2], 1),
		new Upgrade('Reliquary', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Yan Lo', C.Wave2], 1),
		new Upgrade('Brutal Khakkhara', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Yan Lo', C.Wave2], 1),
		new Upgrade('Ash Ascendant', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Ascendant', C.Wave2], 1),
		new Upgrade('Spirit Ascendant', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Ascendant', C.Wave2], 2),
		new Upgrade('Bone Ascendant', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Ascendant', C.Wave2], 3),
		new Upgrade('Pull of the Grave', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Chiaki the Niece', C.Wave2], 1),
		new Upgrade('Command the Graves', [C.TenThunders, C.Resurrectionist], [C.Upgrade, 'Toshiro the Daimyo', C.Wave2], 1),
		new Upgrade('Words on the River', [C.TenThunders], [C.Upgrade, 'Shenlong', C.Wave2], 1),
		new Upgrade('Low River Style', [C.TenThunders], [C.Upgrade, 'Shenlong', 'Sensei Yu', C.Limited, C.Wave2], 2),
		new Upgrade('Fermented River Style', [C.TenThunders], [C.Upgrade, 'Shenlong', 'Sensei Yu', C.Limited, C.Wave2], 2),
		new Upgrade('High River Style', [C.TenThunders], [C.Upgrade, 'Shenlong', 'Sensei Yu', C.Limited, C.Wave2], 2),
		new Upgrade('Wandering River Style', [C.TenThunders], [C.Upgrade, 'Shenlong', 'Sensei Yu', C.Limited, C.Wave2], 2),
		new Upgrade('Promising Disciple', [C.TenThunders], [C.Upgrade, 'Sensei Yu', C.Wave2], 2),
		new Upgrade('By Your Side', [C.TenThunders, C.Guild], [C.Upgrade, 'Sidir Alchibal', C.Wave2], 1),
		new Upgrade('Smoke Grenades', [C.TenThunders], [C.Upgrade, C.NonLeader, C.Rare1, C.Wave2], 1),
		new Upgrade('Hidden Agenda', [C.TenThunders], [C.Upgrade, C.Rare1, C.Wave2], 0),
		new Upgrade('On Wings of Wind', [C.TenThunders], [C.Upgrade, C.Leader, C.Wave2], 2),
		new Upgrade('Blot the Sky', [C.TenThunders], [C.Upgrade, C.Rare1, C.Wave2], 1),
		new Upgrade('Favor of Heaven', [C.TenThunders], [C.Upgrade, C.Rare1, 'Samurai', C.Wave2], 0),
		new Upgrade('Favor of Earth', [C.TenThunders], [C.Upgrade, C.Rare1, 'Samurai', C.Wave2], 0),
		new Upgrade('Favor of Jigoku', [C.TenThunders], [C.Upgrade, C.Rare1, 'Samurai', C.Wave2], 0),
		
		new Upgrade('Mercenary', [], [C.Upgrade], 1),
		
		new Upgrade('Research Grant', [C.Guild], [C.Upgrade, 'Dr. Grimwell', C.Wave3], 1),
		new Upgrade('Conflux of Judgement', [C.Guild], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Incineration', [C.Guild], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of The Hunt', [C.Guild], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Amalgamation', [C.Guild], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Tyranny', [C.Guild], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Brutal Conflux', [C.Guild], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		
		new Upgrade('Conflux of Infamy', [C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Death', [C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Forbidden Knowledge', [C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Spirit', [C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Horror', [C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Carrion Conflux', [C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		
		new Upgrade('Elemental Conflux', [C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Raging Conflux', [C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Illusive Conflux', [C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Ironclad Conflux', [C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Mechanical Conflux', [C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Flaming Conflux', [C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Arcane Conflux', [C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		
		new Upgrade('Strange Alliances', [C.Neverborn], [C.Upgrade, 'Angel Eyes', C.Wave3], 1),
		new Upgrade('Deal at the Crossroads', [C.Neverborn], [C.Upgrade, 'Wrath', C.Wave3], 0),
		new Upgrade('Conflux of Sorrow', [C.Neverborn], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Blood', [C.Neverborn], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Fate', [C.Neverborn], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Music', [C.Neverborn], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Nightmare', [C.Neverborn], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Mysterious Conflux', [C.Neverborn], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		
		new Upgrade('Conflux of Avarice', [C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Nothingness', [C.Outcast, C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Plague', [C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Conflict', [C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Aethereal Conflux', [C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Hodgepodge Conflux', [C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of the Damned', [C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('The Soffocating Injustice', [C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Cursed, C.Wave3], 0),
		new Upgrade('The Monkey\'s Paw', [C.Outcast], [C.Upgrade, C.Trinket, C.Wave3], 0),
		new Upgrade('Vitality Potion', [C.Outcast], [C.Upgrade, C.Trinket, C.Wave3], 0),
		new Upgrade('Memento', [C.Outcast], [C.Upgrade, C.Trinket, C.Wave3], 0),
		new Upgrade('Pretty Floral Bonnet', [C.Outcast], [C.Upgrade, C.Trinket, C.Wave3], 0),
		
		new Upgrade('Conflux of Misfortune', [C.Gremlin], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Inebriation', [C.Gremlin, C.TenThunders], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Blood Ties', [C.Gremlin], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Bacon', [C.Gremlin], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Explosive Force', [C.Gremlin], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Bushwhacking', [C.Gremlin], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Lucky Conflux', [C.Gremlin], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		
		new Upgrade('Conflux of Combat', [C.TenThunders, C.Arcanist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Hunger', [C.TenThunders, C.Neverborn], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Exploration', [C.TenThunders, C.Guild], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of The Dawn', [C.TenThunders], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Conflux of Thunder', [C.TenThunders, C.Outcast], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Ancestral Conflux', [C.TenThunders, C.Resurrectionist], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0),
		new Upgrade('Shadow Conflux', [C.TenThunders], [C.Upgrade, C.EmissaryOfFate, C.Wave3], 0)
	]
};